### ISSUE TITLE
Prints version on import

### ISSUE THREAD

**Issue by djmitche** [prmiles/pymcmcstat#41]
**Describe the bug**
pymcmcstat prints its version when imported

**Expected behavior**
Imports occur without side-effects, and in particular no output.

It's pretty atypical for a Python module to write to stdout on import, and would make it a bit awkward to fit this into a larger command-line application, for example (since it would be included in that application's output).

Refs https://github.com/openjournals/joss-reviews/issues/1417

**Comment by djmitche** [comment]
Thanks for the tests too :)

**Comment by prmiles** [comment]
Thank you for pointing out the issue.  I am still somewhat new to Python :)
