### ISSUE TITLE
JOSS Paper Link

### ISSUE THREAD

**Issue by katyhuff** [prmiles/pymcmcstat#56]
**Describe the bug**
In paper.md, there's a link that is formatted like so:

```
(I'm an inline-style link)[https://www.google.com]
```

But, Markdown prefers the opposite order, square brackets followed by parenthesis:
```
[I'm an inline-style link](https://www.google.com)
```

**To Reproduce**
Currently, `(mcmcstat)[https://mjlaine.github.io/mcmcstat/]` looks funky in the paper... like 
(mcmcstat)[https://mjlaine.github.io/mcmcstat/].

**Expected behavior**
@prmiles would prefer [mcmcstat](https://mjlaine.github.io/mcmcstat/).

**Suggested solution**
I think this issue can be solved if one replaces `(mcmcstat)[https://mjlaine.github.io/mcmcstat/]` with `[mcmcstat](https://mjlaine.github.io/mcmcstat/)` in paper.md.

This issue can be closed if the resulting JOSS paper renders nicely.

**Comment by prmiles** [comment]
Thanks for finding my mistake!

**Comment by katyhuff** [comment]
No problem - super common.
