### ISSUE TITLE
Can I get the vhb4910 data?

### ISSUE THREAD

**Issue by Huzaifg** [prmiles/pymcmcstat#96]
Hello and thank you for this easy to use package. 
I am currently trying to get my head around some of the features of the package and was looking at the viscoelastic model example. 
I was wondering if I can get my hands on the vhb4910 data so that I can play around with the model a bit.

**Comment by prmiles** [comment]
@Huzaifg Glad to hear you are enjoying the package!

I believe the data set you want is included in the [pymcmcstat_examples](https://github.com/prmiles/pymcmcstat_examples/tree/master/data_files) repository.  

https://github.com/prmiles/pymcmcstat_examples

Note, you can launch a Binder session from that repo (or using the link below) and interact with the examples directly.  Not sure if that would be useful for you (or if Binder is even working anymore), but wanted to share the info :)

https://mybinder.org/v2/gh/prmiles/pymcmcstat_examples/master

Hope that helps!  I'll close the issue in about a week if I don't hear anything else.

**Comment by Huzaifg** [comment]
@prmiles Great thanks! I see it now.
